###
POST http://localhost:8080/stop

###
POST http://localhost:8080/kafka/producer/start

###
POST http://localhost:8080/kafka/producer/stop

###
POST http://localhost:8080/kafka/consumer/start

###
POST http://localhost:8080/kafka/consumer/stop
